\" utop.1
\" ------
\" Copyright : (c) 2011, Jeremie Dimino <jeremie@dimino.org>
\" Licence   : BSD3
\"
\" This file is a part of utop.

.TH UTOP 1 "August 2011"

.SH NAME
utop \- Universal toplevel for OCaml

.SH SYNOPSIS
.B utop
[
.I options
]
[
.I object-files
]
[
.I script-file
]

.SH DESCRIPTION

.B utop
is a enhanced toplevel for OCaml with many features, including context
sensitive completion.

When you start
.B utop
what you see is the prompt followed by a bar containing words. This is
the completion bar, it contains the possible completion and is updated
as you type. The highlighted word in the completion bar is the
selected word. You can navigate using the keys Alt+Left and Alt+Right
and you can complete using the currently selected word by pressing
Alt+Tab (you can configure these bindings in the file
.I ~/.lambda-term-inputrc
, see
.BR lambda-term-inputrc (5)
for details).

utop supports completion on:

        * directives and directive arguments
        * identifiers
        * record fields
        * variants
        * function labels
        * object methods

Colors are by default configured for terminals with dark colors, such
as white on black, so the prompt may looks too bright on light colors
terminals. You can change that by setting the color profile of
utop. For that type:

        UTop.set_profile UTop.Light;;

You can then add this line to your
.I ~/.ocamlinit
file.

You can enable basic syntax highlighting in utop by writing a
.I ~/.utoprc
file. See
.BR utoprc (5)
for that.

Finally utop can run in emacs. For that you have to add the following line to your
.I ~/.emacs
file:

        (autoload 'utop "utop" "Toplevel for OCaml" t)

then you can run utop by pressing M-x and typing "utop". utop support
completion in emacs mode. Just press Tab to complete a word. You can
also integrate it with the tuareg, caml or typerex mode. For that add
the following lines to your
.I ~/.emacs
file:

        (autoload 'utop-minor-mode "utop" "Minor mode for utop" t)
        (add-hook 'tuareg-mode-hook 'utop-minor-mode)

.SH OPTIONS
Same as
.BR ocaml (1).

.SH FILES
.I ~/.ocamlinit
.RS
The initialization file of the toplevel.
.RE
.I ~/.utoprc
.RS
The configuration file for utop. See
.BR utoprc (5).
.RE
.I ~/.lambda-term-inputrc
.RS
The file containing key bindings. See
.BR lambda-term-inputrc (5).

.SH AUTHOR
Jérémie Dimino <jeremie@dimino.org>

.SH "SEE ALSO"
.BR utoprc (5),
.BR lambda-term-inputrc (5),
.BR ocaml (1).
